# Generated by Django 2.1.2 on 2018-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_mymodel3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_email', models.CharField(max_length=35)),
                ('my_pass', models.CharField(max_length=35)),
                ('my_phone', models.CharField(max_length=35)),
            ],
        ),
    ]
