# Generated by Django 2.1.2 on 2018-10-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_email_from', models.CharField(max_length=35)),
                ('my_email_to', models.CharField(max_length=35)),
                ('my_email_cc', models.CharField(max_length=35)),
                ('my_email_sub', models.CharField(max_length=35)),
                ('my_email_compose', models.CharField(max_length=400)),
            ],
        ),
    ]
