# Generated by Django 2.1.2 on 2018-10-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updation_regarding', models.CharField(max_length=35)),
                ('any_important_message', models.CharField(max_length=500)),
                ('deadline', models.CharField(max_length=35)),
                ('noticeadddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
