# Generated by Django 2.1.2 on 2018-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='update',
            name='updation_regarding',
            field=models.CharField(max_length=100),
        ),
    ]
